version: "3.9"
services:
  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=group06
      - RABBITMQ_DEFAULT_PASS=group06
    ports:
      - 5672:5672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  db:
    build: ./sender/db
    environment:
      - POSTGRES_PASSWORD=group06
      - POSTGRES_DB=sender
  sender:
    build: ./sender
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sender
      - POSTGRES_PWD=group06
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=group06
      - RABBITMQ_PASSWORD=group06
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
      - db
